ARG HELM_VERSION
ARG NODE_VERSION

FROM ${GH_IMAGE:-ghcr.io/gperdomor/nx-docker}:${NODE_VERSION}-alpine
ENV BASE_URL="https://get.helm.sh"
ENV TAR_FILE="helm-v${HELM_VERSION:-3.5.4}-linux-amd64.tar.gz"
RUN curl -L ${BASE_URL}/${TAR_FILE} |tar xvz && \
    mv linux-amd64/helm /usr/bin/helm && \
    chmod +x /usr/bin/helm && \
    rm -rf linux-amd64 && \
    rm -f /var/cache/apk/*

WORKDIR /code

CMD ["sh"]
