name: 'Find missing tags'
description: 'Fetch missing tags for nx-builder images'
inputs:
  ignored-tags: # id of input
    description: 'Ignored tags'
    required: false
    default: ''
outputs:
  matrix:
    description: 'Missing tags to build'
  empty_matrix:
    description: 'The matrix is empty?'
  latest:
    description: 'Node version for latest tag'
runs:
  using: 'node16'
  main: 'main.js'
