version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'America/Santiago'
    commit-message:
      prefix: 'ci'
      include: 'scope'